name: Update parent repository

on:
  push:
    branches:
      - main # 监听子仓库 main 分支的推送事件

jobs:
  update-parent-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parent repository
        uses: actions/checkout@v3 # 检出父仓库代码
        with:
          ref: 'main' # 检出父仓库 main 分支的代码
          submodules: 'recursive'
          repository: 'Web-Engineering-XDU/Web-Engineering-Project'
          token: ${{secrets.TOKEN}}
      - name: Update submodule and commit
        run: |
          cd backend
          git checkout main
          git pull
          cd ..
          git config --global user.email "1023797278@qq.com"
          git config --global user.name "Guchen"
          git add .
          git commit -m "Update Frontend"
          git push
